name: Android Instrumentation Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
     name: Running Android Tests
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: SetupAndroidSDK
        uses: android-actions/setup-android@v2
        with:
           api-level: 33

      - name: Installspecificbuildtools
        run: sdkmanager "build-tools;33.0.0"

      - name: SetupAndStartAndroidEmulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
           api-level: 33
           target: default
           arch: x86_64
           emulator-options: -no-boot-anim-no-audio-no-snapshot-load
           script: ./gradlewconnectedAndroidTest

      - name: Buildtheapp
        run: ./gradlewassembleDebug

      - name: Run Android Tests
        run: ./gradlew connectedAndroidTest --continue

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'