name: AndroidInstrumentationTests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
     name: Running Android Tests
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run Android Tests
        run: ./gradlew connectedAndroidTest --continue
      - name: SetupAndroidSDK
        uses: android-actions/setup-android@v2
        with:
           api-level: 34
      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: app/build/reports/androidTests/connected/