name: Android Instrumentation Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
    name: Running Android Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: SetupAndroidSDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33

      - name: Installspecificbuildtools
        run: sdkmanager "build-tools;34.0.0"

      - name: Create AVD
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"


      - name: SetupAndStartAndroidEmulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd your_avd_name -no-skin -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Build the app
        run: ./gradlewassembleDebug

      - name: Run Android Tests
        run: ./gradlew connectedAndroidTest --continue

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'