name: Local Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  local_test_job:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Debug Tests
        run: ./gradlew test --continue

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/build/reports/tests/'